<?php

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\Tests\Component\Foo\FunctionalJavascriptTest;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Twig\Node\CheckToStringNode;

/**
 * Implements hook_theme().
 */
function events_module_theme() {
  return [
    'views_view_unformatted__events__page_1' => [
      'template' => 'views-view-unformatted--events--page-1',
      'base hook' => 'view'
    ],
    'views_view_unformatted__frontpage__page_1' => [
      'template' => 'views-view-unformatted--frontpage--page-1',
      'base hook' => 'view'
    ],
    'views_view__frontpage__page_1' => [
      'template' => 'views-view--frontpage--page-1',
      'base hook' => 'view'
    ],
    'views_view__events__page_1' => [
      'template' => 'views-view--events--page-1',
      'base hook' => 'view'
    ],
    'fieldset__field_date_value_1_wrapper' => [
      'template' => 'fieldset--field-date-value-1-wrapper',
      'base hook' => 'fieldset'
    ],
    'paragraph__block_with_text_and_image__default' => [
      'template' => 'paragraph--block-with-text-and-image--default',
      'base hook' => 'paragraph'
    ],
  ];
}

/**
 * Implements template_preprocess_views_view_unformatted().
 */
function events_module_preprocess_views_view_unformatted(&$variables) {

    $route_name = \Drupal::routeMatch()->getRouteName();

    if($route_name == 'view.events.page_1' || $route_name == "view.frontpage.page_1")
    {
      $variables['#attached']['library'][] = 'events_module/datepicker';
      $variables['#attached']['library'][] = 'events_module/custom';
    }
}

/**
 * Implements template_preprocess_views_view().
 */
function events_module_preprocess_views_view(&$variables) {

    if ($variables['id'] == 'frontpage')
    {
        $home_events_text = \Drupal::config('events_module.settings')->get('home_events_text');
        $variables['home_events_text'] = $home_events_text;
    }

    if ($variables['id'] == 'events')
    {
        $events_no_results_text = \Drupal::config('events_module.settings')->get('events_no_results_text');
        $variables['empty'] = $events_no_results_text;
    }
}

/**
 * Implements hook_form_alter().
 */
function events_module_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'node_event_form' || $form_id == 'node_event_edit_form') {
    $form['#validate'][] = 'events_module_node_form_validate';
  }
}

/**
 * Validation form for the waarde_voorwerp form.
 *
 * Check if event title starts with the capital letter
 */
function events_module_node_form_validate($form, FormStateInterface $form_state) {

  $title = $form_state->getValue('title')[0]['value']; 

  if (!starts_with_upper($title)) {
    $form_state->setErrorByName('title', 'Notikuma nosaukumam jāsākas ar lielo burtu');
  } 
}

/**
 * Check if given string starts with the capital letter
 */
function starts_with_upper($str) {
  $chr = mb_substr ($str, 0, 1, "UTF-8");
  return mb_strtolower($chr, "UTF-8") != $chr;
}

/**
 * Implements hook_views_query_alter().
 */
function events_module_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  if ($view->id() == 'events' && $_GET != []) {

    if ($_GET['field_date_value_1'] != "") {

      // unset this input default query rule
      unset($query->where[1]['conditions'][3]);

      $dateRange = explode(" - ", $_GET['field_date_value_1']);

      // override minimum date query rule 
      $query->where[1]['conditions'][2]['field'] = "DATE_FORMAT(node__field_date.field_date_value, '%Y-%m-%d') BETWEEN DATE_FORMAT('{$dateRange[0]}', '%Y-%m-%d') AND DATE_FORMAT('{$dateRange[1]}', '%Y-%m-%d')";
    }
  }
}

/*
 * Implements hook_theme_suggestions_HOOK_alter()
 */
function events_module_theme_suggestions_fieldset_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'fieldset__' . $variables['element']['#parents'][0];
}

/*
 * Implements template_preprocess_paragraph__PARAGRAPH_TYPE()
 */
function events_module_preprocess_paragraph__block_with_text_and_image(&$variables) {
  
  $route_name = \Drupal::routeMatch()->getRouteName();

  // dump($variables['content']['field_link_to_content'][0]['#url']);

  if ($route_name == 'entity.node.canonical') {

    $variables['#attached']['library'][] = 'events_module/custom';
  }
}